# This is a basic workflow to help you get started with Actions

name: PyenvVersionSync

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: 0 21 * * *
  push:
    branches: sentry

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
  EARTHLY_ORG: jahands
  EARTHLY_SATELLITE: mini-sat
  FORCE_COLOR: 1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access i
      - uses: earthly/actions-setup@v1.0.13
        with:
          version: v0.8.15

      - name: Install Ubi
        run: |
          mkdir -p "$HOME/bin"
          export PATH="$HOME/bin:$PATH"
          curl -fsSL https://sh.uuid.rocks/install/ubi | bash
      - name: Install Sentry CLI
        run: ubi -p getsentry/sentry-cli

      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Build & Sync Pyenv DB
        # note: not using --ci here so that it outputs api/database.json
        run: earthly --push +sync-pyenv-db

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet || git commit -m "Update python version" -a
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
