# This is a basic workflow to help you get started with Actions

name: PyenvVersionSync

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: 42 21 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Dagger
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: '0.18.16'
      - name: Install Ubi
        run: |
          mkdir -p "$HOME/bin"
          echo "$HOME/bin" >> $GITHUB_PATH
          curl -fsSL https://sh.uuid.rocks/install/ubi | bash
      - name: Install Sentry CLI
        run: ubi -p getsentry/sentry-cli -i "$HOME/bin"

      - name: Build & Sync Pyenv DB
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FORCE_COLOR: 1
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          sentry-cli monitors run pyenv-version-sync -- \
            dagger call sync-pyenv-db \
              --AWS_ACCESS_KEY_ID=env://AWS_ACCESS_KEY_ID \
              --AWS_SECRET_ACCESS_KEY=env://AWS_SECRET_ACCESS_KEY

          # Export database.json for git commit
          dagger call build-pyenv-db export --path=api/

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet || git commit -m "Update python version" -a
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
